name = "Custom Theme"
license = "MIT"
licenselink = "https://github.com/yourname/hugo-theme/blob/master/LICENSE"
description = "A simple and clean Hugo theme"
homepage = "https://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "黄国位"
  homepage = "https://guoweihuang.github.io/"

[original]
  name = "Custom Theme"
  homepage = "https://example.com/"
  repo = "https://github.com/yourname/hugo-theme" 