name = "Custom Theme"
license = "MIT"
licenselink = "https://github.com/guoweihuang/guoweihuang.github.io/blob/main/LICENSE"
description = "A simple and clean Hugo theme for technical blog"
homepage = "https://www.huangguowei.com/"
tags = ["blog", "clean", "responsive", "technical"]
features = ["responsive", "clean-design", "fast"]
min_version = "0.41.0"

[author]
  name = "黄国位"
  homepage = "https://www.huangguowei.com/"

[original]
  name = "Custom Theme"
  homepage = "https://www.huangguowei.com/"
  repo = "https://github.com/guoweihuang/guoweihuang.github.io"
